apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
  name: api
  namespace: default
spec:
  template:
    metadata:
      labels:
        ictsc2018-score: api
    spec:
      containers:
        - image: upluse10/ictsc-score-server:api
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 8900
              name: api
          envFrom:
            - configMapRef:
                name: api-env
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-env
  namespace: default
data:
  TZ: "Asia/Tokyo"
  RACK_ENV: "production"
  RAILS_ENV: "production"
  MYSQL_HOST: "db"
  MYSQL_PORT: "3306"
  MYSQL_USER: "root"
  MYSQL_DATABASE: "ictsc_score_server"
  MYSQL_PASSWORD: "PASSWORD"
  MYSQL_ROOT_PASSWORD: "PASSWORD"
  API_SESSION_USE_REDIS: "y"
  API_SESSION_COOKIE_KEY: "ictsc_score_server"
  API_SESSION_COOKIE_SECRET: "SECRET"
  API_SESSION_REDIS_SERVER: "redis://redis:6379/0"
  API_CONTEST_REDIS_REALTIME_NOTIFICATION_CHANNEL: "realtime_notification"
  PLASMA_SUBSCRIBER_REDIS_ADDR: "redis:6379"
  PLASMA_SUBSCRIBER_REDIS_CHANNELS: "realtime_notification"
  REDIS_URL: "redis://redis:6379/0"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    ictsc2018-score: api
  name: api
  namespace: default
spec:
  ports:
    - name: api
      port: 8900
      targetPort: 8900
      nodePort: 30080
  selector:
    ictsc2018-score: api
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  namespace: default
  annotations:
    nginx.org/server-snippet: "proxy_ssl_verify off;"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - contest.icttoracon.net
      secretName: contest
  rules:
    - host: contest.icttoracon.net
      http:
        paths:
          - path: /api
            backend:
              serviceName: api
              servicePort: 8900
