apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: certificate # 証明書を格納するSecretにつける名前
  namespace: default
spec:
  secretName: cert-manager-tls # 証明書を格納するSecretにつける名前
  issuerRef:
    # ClusterIssuerを指定する。
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
      - _VAR_DEV_CONTEST_FQDN # ドメイン
      - _VAR_PROD_CONTEST_FQDN # ドメイン
      - _VAR_TRAINING_CONTEST_FQDN
  acme:
    config:
    - dns01:
        provider: cloudflare
      domains:
      - _VAR_DEV_CONTEST_FQDN # ドメイン
      - _VAR_PROD_CONTEST_FQDN # ドメイン
      - _VAR_TRAINING_CONTEST_FQDN

    # - http01:
    #       ingressClass: ingress # 使用しているIngressの名前
    #   domains:
    #   - 'training.contest.ictsc.net' # ドメイン
