apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    ictsc2018-score: ui
  name: ui
spec:
  template:
    metadata:
      labels:
        ictsc2018-score: ui
    spec:
      containers:
        - image: upluse10/ictsc-score-server:ui
          imagePullPolicy: Always
          name: ui
          ports:
            - name: ui
              containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    ictsc2018-score: ui
  name: ui
spec:
  ports:
    - name: ui
      port: 80
      targetPort: 80
  selector:
    ictsc2018-score: ui
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui
  annotations:
    nginx.org/server-snippet: "proxy_ssl_verify off;"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "nginx"
    #ingress.kubernetes.io/whitelist-source-range: "172.16.0.0/12,10.0.0.0/8"
spec:
  tls:
    - hosts:
        - contest.icttoracon.net
      secretName: contest
  rules:
    - host: contest.icttoracon.net
      http:
        paths:
          - path: /
            backend:
              serviceName: ui
              servicePort: 80
